// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNllogH3NAoVdSl_JOzeYQra1yxgBzYvY',
    appId: '1:375946103982:web:68ba9cdbc55f6468cef13f',
    messagingSenderId: '375946103982',
    projectId: 'fir-test-61ede',
    authDomain: 'fir-test-61ede.firebaseapp.com',
    storageBucket: 'fir-test-61ede.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnZZkMRXd_0NRgfzCvwAvNOt1XRyVUBQY',
    appId: '1:375946103982:android:fc53ed4871d98f37cef13f',
    messagingSenderId: '375946103982',
    projectId: 'fir-test-61ede',
    storageBucket: 'fir-test-61ede.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0fJKB2OLuB_y8jhOp4RForu6f-fXScj8',
    appId: '1:375946103982:ios:8c5a82407944bec2cef13f',
    messagingSenderId: '375946103982',
    projectId: 'fir-test-61ede',
    storageBucket: 'fir-test-61ede.appspot.com',
    iosClientId:
        '375946103982-fk6fl0pr7ljlp6eo6o95cspq9tjq0vgj.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0fJKB2OLuB_y8jhOp4RForu6f-fXScj8',
    appId: '1:375946103982:ios:8c5a82407944bec2cef13f',
    messagingSenderId: '375946103982',
    projectId: 'fir-test-61ede',
    storageBucket: 'fir-test-61ede.appspot.com',
    iosClientId:
        '375946103982-fk6fl0pr7ljlp6eo6o95cspq9tjq0vgj.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasee',
  );
}
